"""initial schema

Revision ID: 7aa473382699
Revises: 0001_db_infra
Create Date: 2026-02-06 17:57:43.217588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002_initial_schema'
down_revision: Union[str, Sequence[str], None] = '0001_db_infra'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grading_criteria',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    sa.UniqueConstraint('code'),
    schema='public'
    )
    op.create_index('uq_grading_criteria_uuid', 'grading_criteria', ['uuid'], unique=True, schema='public')
    op.create_index('uq_grading_criteria_code', 'grading_criteria', ['code'], unique=True, schema='public')
    op.create_table('students',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_index('idx_students_active', 'students', ['active'], unique=False, schema='public')
    op.create_index('idx_students_email', 'students', ['email'], unique=False, schema='public')
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('user_type', sa.String(length=50), server_default=sa.text("'teacher'"), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovery_code_hash', sa.Text(), nullable=True),
    sa.Column('recovery_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovery_code_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('recovery_code_attempts >= 0', name='chk_users_recovery_code_attempts'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_index('idx_users_active', 'users', ['active'], unique=False, schema='public')
    op.create_index('idx_users_email', 'users', ['email'], unique=False, schema='public')
    op.create_index('idx_users_recovery_code_expires_at', 'users', ['recovery_code_expires_at'], unique=False, schema='public')
    op.create_index('idx_users_uuid', 'users', ['uuid'], unique=True, schema='public')
    op.create_table('auth_refresh_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('subject', sa.UUID(), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('token_type', sa.String(length=20), server_default=sa.text("'REFRESH'"), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('key_status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.TEXT()), nullable=False),
    sa.Column('issued_ip', postgresql.INET(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("key_status IN ('ACTIVE', 'ROTATED', 'REVOKED', 'EXPIRED')", name='chk_key_status'),
    sa.CheckConstraint("token_type = 'REFRESH'", name='chk_token_type'),
    sa.CheckConstraint('issued_at <= not_before AND not_before < expires_at', name='chk_token_dates'),
    sa.ForeignKeyConstraint(['subject'], ['public.users.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_auth_refresh_tokens_jti', 'auth_refresh_tokens', ['jti'], unique=True, schema='public')
    op.create_index('idx_auth_refresh_tokens_subject', 'auth_refresh_tokens', ['subject'], unique=False, schema='public')
    op.create_index('idx_auth_refresh_tokens_valid', 'auth_refresh_tokens', ['subject', 'expires_at'], unique=False, schema='public', postgresql_where=sa.text("revoked_at IS NULL AND key_status = 'ACTIVE'"))
    op.create_table('classes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('teacher_uuid', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['public.users.uuid'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_uuid'], ['public.users.uuid'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_index('idx_classes_active', 'classes', ['active'], unique=False, schema='public')
    op.create_index('idx_classes_created_by', 'classes', ['created_by'], unique=False, schema='public')
    op.create_index('idx_classes_year', 'classes', ['year'], unique=False, schema='public')
    op.create_index('uq_classes_uuid', 'classes', ['uuid'], unique=True, schema='public')
    op.create_table('class_students',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('class_uuid', sa.UUID(), nullable=False),
    sa.Column('student_uuid', sa.UUID(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.ForeignKeyConstraint(['class_uuid'], ['public.classes.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_uuid'], ['public.students.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index('idx_class_students_class', 'class_students', ['class_uuid'], unique=False, schema='public')
    op.create_index('idx_class_students_student', 'class_students', ['student_uuid'], unique=False, schema='public')
    op.create_index(op.f('ix_public_class_students_student_uuid'), 'class_students', ['student_uuid'], unique=False, schema='public')
    op.create_table('exams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('class_uuid', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','PUBLISHED','ARCHIVED', 'FINISHED')", name='chk_exams_status'),
    sa.CheckConstraint('starts_at IS NULL OR ends_at IS NULL OR starts_at < ends_at', name='chk_exams_window'),
    sa.ForeignKeyConstraint(['class_uuid'], ['public.classes.uuid'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['public.users.uuid'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_index('idx_exams_active', 'exams', ['active'], unique=False, schema='public')
    op.create_index('idx_exams_class_uuid', 'exams', ['class_uuid'], unique=False, schema='public')
    op.create_index('idx_exams_created_by', 'exams', ['created_by'], unique=False, schema='public')
    op.create_index('idx_exams_status', 'exams', ['status'], unique=False, schema='public')
    op.create_table('attachments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exam_uuid', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_uuid'], ['public.exams.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_index('idx_attachments_exam_uuid', 'attachments', ['exam_uuid'], unique=False, schema='public')
    op.create_index('idx_attachments_sha256_hash', 'attachments', ['sha256_hash'], unique=False, schema='public')
    op.create_table('exam_criteria',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exam_uuid', sa.UUID(), nullable=False),
    sa.Column('criteria_uuid', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), server_default=sa.text('1.0'), nullable=False),
    sa.Column('max_points', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('weight > 0', name='chk_exam_criteria_weight'),
    sa.ForeignKeyConstraint(['criteria_uuid'], ['public.grading_criteria.uuid'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exam_uuid'], ['public.exams.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_index('idx_exam_criteria_exam_uuid', 'exam_criteria', ['exam_uuid'], unique=False, schema='public')
    op.create_table('exam_questions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exam_uuid', sa.UUID(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('points', sa.Numeric(precision=8, scale=2), server_default=sa.text('1.00'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('points >= 0', name='chk_exam_questions_points'),
    sa.CheckConstraint('question_order >= 1', name='chk_exam_questions_order'),
    sa.ForeignKeyConstraint(['exam_uuid'], ['public.exams.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_index('idx_exam_questions_active', 'exam_questions', ['active'], unique=False, schema='public')
    op.create_index('idx_exam_questions_exam_uuid', 'exam_questions', ['exam_uuid'], unique=False, schema='public')
    op.create_index('uq_exam_questions_exam_order', 'exam_questions', ['exam_uuid', 'question_order'], unique=True, schema='public')
    op.create_index('uq_exam_questions_uuid', 'exam_questions', ['uuid'], unique=True, schema='public')
    op.create_table('exam_question_criteria_override',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('question_uuid', sa.UUID(), nullable=False),
    sa.Column('criteria_uuid', sa.UUID(), nullable=False),
    sa.Column('weight_override', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_points_override', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('weight_override IS NULL OR weight_override > 0', name='chk_eqco_weight'),
    sa.ForeignKeyConstraint(['criteria_uuid'], ['public.grading_criteria.uuid'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_uuid'], ['public.exam_questions.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_index('idx_eqco_question_uuid', 'exam_question_criteria_override', ['question_uuid'], unique=False, schema='public')
    op.create_table('student_answers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exam_uuid', sa.UUID(), nullable=False),
    sa.Column('question_uuid', sa.UUID(), nullable=False),
    sa.Column('student_uuid', sa.UUID(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'SUBMITTED'"), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint("status IN ('SUBMITTED','GRADED','INVALID')", name='chk_student_answers_status'),
    sa.CheckConstraint('score IS NULL OR score >= 0', name='chk_student_answers_score'),
    sa.ForeignKeyConstraint(['exam_uuid'], ['public.exams.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graded_by'], ['public.users.uuid'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_uuid'], ['public.exam_questions.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_uuid'], ['public.students.uuid'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_index('idx_student_answers_exam', 'student_answers', ['exam_uuid'], unique=False, schema='public')
    op.create_index('idx_student_answers_question', 'student_answers', ['question_uuid'], unique=False, schema='public')
    op.create_index('idx_student_answers_status', 'student_answers', ['status'], unique=False, schema='public')
    op.create_index('idx_student_answers_student', 'student_answers', ['student_uuid'], unique=False, schema='public')
    op.create_index('uq_student_answers_student_exam_question', 'student_answers', ['student_uuid', 'exam_uuid', 'question_uuid'], unique=True, schema='public')
    op.create_index('uq_student_answers_uuid', 'student_answers', ['uuid'], unique=True, schema='public')
    op.create_table('student_answer_criteria_scores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('student_answer_uuid', sa.UUID(), nullable=False),
    sa.Column('criteria_uuid', sa.UUID(), nullable=False),
    sa.Column('raw_score', sa.Numeric(precision=8, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('weighted_score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('raw_score >= 0', name='chk_sacs_raw_score'),
    sa.ForeignKeyConstraint(['criteria_uuid'], ['public.grading_criteria.uuid'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_answer_uuid'], ['public.student_answers.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    schema='public'
    )
    op.create_index('idx_sacs_answer', 'student_answer_criteria_scores', ['student_answer_uuid'], unique=False, schema='public')
    op.create_index('idx_sacs_criteria', 'student_answer_criteria_scores', ['criteria_uuid'], unique=False, schema='public')
    op.create_index('uq_sacs_answer_criteria', 'student_answer_criteria_scores', ['student_answer_uuid', 'criteria_uuid'], unique=True, schema='public')
    op.create_index('uq_sacs_uuid', 'student_answer_criteria_scores', ['uuid'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_sacs_uuid', table_name='student_answer_criteria_scores', schema='public')
    op.drop_index('uq_sacs_answer_criteria', table_name='student_answer_criteria_scores', schema='public')
    op.drop_index('idx_sacs_criteria', table_name='student_answer_criteria_scores', schema='public')
    op.drop_index('idx_sacs_answer', table_name='student_answer_criteria_scores', schema='public')
    op.drop_table('student_answer_criteria_scores', schema='public')
    op.drop_index('uq_student_answers_uuid', table_name='student_answers', schema='public')
    op.drop_index('uq_student_answers_student_exam_question', table_name='student_answers', schema='public')
    op.drop_index('idx_student_answers_student', table_name='student_answers', schema='public')
    op.drop_index('idx_student_answers_status', table_name='student_answers', schema='public')
    op.drop_index('idx_student_answers_question', table_name='student_answers', schema='public')
    op.drop_index('idx_student_answers_exam', table_name='student_answers', schema='public')
    op.drop_table('student_answers', schema='public')
    op.drop_index('idx_eqco_question_uuid', table_name='exam_question_criteria_override', schema='public')
    op.drop_table('exam_question_criteria_override', schema='public')
    op.drop_index('uq_exam_questions_uuid', table_name='exam_questions', schema='public')
    op.drop_index('uq_exam_questions_exam_order', table_name='exam_questions', schema='public')
    op.drop_index('idx_exam_questions_exam_uuid', table_name='exam_questions', schema='public')
    op.drop_index('idx_exam_questions_active', table_name='exam_questions', schema='public')
    op.drop_table('exam_questions', schema='public')
    op.drop_index('idx_exam_criteria_exam_uuid', table_name='exam_criteria', schema='public')
    op.drop_table('exam_criteria', schema='public')
    op.drop_index('idx_attachments_sha256_hash', table_name='attachments', schema='public')
    op.drop_index('idx_attachments_exam_uuid', table_name='attachments', schema='public')
    op.drop_table('attachments', schema='public')
    op.drop_index('idx_exams_status', table_name='exams', schema='public')
    op.drop_index('idx_exams_created_by', table_name='exams', schema='public')
    op.drop_index('idx_exams_class_uuid', table_name='exams', schema='public')
    op.drop_index('idx_exams_active', table_name='exams', schema='public')
    op.drop_table('exams', schema='public')
    op.drop_index(op.f('ix_public_class_students_student_uuid'), table_name='class_students', schema='public')
    op.drop_index('idx_class_students_student', table_name='class_students', schema='public')
    op.drop_index('idx_class_students_class', table_name='class_students', schema='public')
    op.drop_table('class_students', schema='public')
    op.drop_index('uq_classes_uuid', table_name='classes', schema='public')
    op.drop_index('idx_classes_year', table_name='classes', schema='public')
    op.drop_index('idx_classes_created_by', table_name='classes', schema='public')
    op.drop_index('idx_classes_active', table_name='classes', schema='public')
    op.drop_table('classes', schema='public')
    op.drop_index('idx_auth_refresh_tokens_valid', table_name='auth_refresh_tokens', schema='public', postgresql_where=sa.text("revoked_at IS NULL AND key_status = 'ACTIVE'"))
    op.drop_index('idx_auth_refresh_tokens_subject', table_name='auth_refresh_tokens', schema='public')
    op.drop_index('idx_auth_refresh_tokens_jti', table_name='auth_refresh_tokens', schema='public')
    op.drop_table('auth_refresh_tokens', schema='public')
    op.drop_index('idx_users_uuid', table_name='users', schema='public')
    op.drop_index('idx_users_recovery_code_expires_at', table_name='users', schema='public')
    op.drop_index('idx_users_email', table_name='users', schema='public')
    op.drop_index('idx_users_active', table_name='users', schema='public')
    op.drop_table('users', schema='public')
    op.drop_index('idx_students_email', table_name='students', schema='public')
    op.drop_index('idx_students_active', table_name='students', schema='public')
    op.drop_table('students', schema='public')
    op.drop_index('uq_grading_criteria_uuid', table_name='grading_criteria', schema='public')
    op.drop_index('uq_grading_criteria_code', table_name='grading_criteria', schema='public')
    op.drop_table('grading_criteria', schema='public')
    # ### end Alembic commands ###
